AWSTemplateFormatVersion: 2010-09-09
Description: Campaign Manager's EC2 instance for Recommender files packaging
Parameters:
  KeyName:
    Description: Key Pair name
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: bigdatakp
  Subnet:
    Description: Subnet to launch services in
    Type: 'AWS::EC2::Subnet::Id'
    Default: subnet-a69ac8cc
  VPC:
    Description: VPC to launch services in
    Type: 'AWS::EC2::VPC::Id'
    Default: vpc-ee8d3285
  NatSG:
    Type: String
    Description: SG Id Nat QAS
    Default: sg-7162cb0b
  BastionSG:
    Type: String
    Description: SG Id Bastion QAS
    Default: sg-0cd93949f3e18e7d0
Mappings:
  RegionAMIMap:
    ap-northeast-1:
      AmazonLinux: ami-cbf90ecb
    ap-southeast-1:
      AmazonLinux: ami-68d8e93a
    ap-southeast-2:
      AmazonLinux: ami-fd9cecc7
    eu-central-1:
      AmazonLinux: ami-a8221fb5
    eu-west-1:
      AmazonLinux: ami-a10897d6
    sa-east-1:
      AmazonLinux: ami-b52890a8
    us-east-1:
      AmazonLinux: ami-1ecae776
    us-west-1:
      AmazonLinux: ami-d114f295
    us-west-2:
      AmazonLinux: ami-e7527ed7
Resources:
  InstanceProfileRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: bigdata_cm_EC2ForS3
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: ReadWriteForS3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:PutObjectAcl'
                  - 's3:GetObject'
                  - 's3:GetObjectAcl'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource:
                  - 'arn:aws:s3:::forecast-events-test/*'
                  - 'arn:aws:s3:::forecast-events-test'
                  - 'arn:aws:s3:::belc-bigdata-functional-dlk-qas/*'
                  - 'arn:aws:s3:::belc-bigdata-functional-dlk-qas'
                  - 'arn:aws:s3:::belc-bigdata-cm-data-qas/*'
                  - 'arn:aws:s3:::belc-bigdata-cm-data-qas'
                  - 'arn:aws:s3:::belc-bigdata-apps-shared-qas/*'
                  - 'arn:aws:s3:::belc-bigdata-apps-shared-qas'
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref InstanceProfileRole
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: SG_BIGDATA_CM_BASH_QAS
      GroupDescription: CM for Recommender
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 172.19.64.0/20
          Description: Red Belcorp Wifi
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 172.19.2.0/23
          Description: Red Belcorp Piso 4
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref NatSG
          Description: Nat QAS
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref NatSG
          Description: Nat QAS
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref BastionSG
          Description: Bastion QAS
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap 
        - RegionAMIMap
        - !Ref 'AWS::Region'
        - AmazonLinux
      InstanceType: t2.micro
      SubnetId: !Ref Subnet
      UserData: !Base64 
        'Fn::Join':
          - ''
          - []
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref SecurityGroup
      IamInstanceProfile: !Ref InstanceProfile
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: io1
            Iops: '700'
            DeleteOnTermination: 'true'
            VolumeSize: '30'
      Tags:
        - Key: CTLAdmin
          Value: 'NO'
        - Key: Direccion
          Value: BIGDATA
        - Key: Entorno
          Value: QAS
        - Key: Grupo
          Value: BIGDATA
        - Key: Name
          Value: EC2LNX_BIGDATA_CM_QAS
        - Key: ServerRol
          Value: Servicio
        - Key: Tipo
          Value: Proyecto
Outputs:
  InstanceId:
    Value: !Ref EC2Instance
    Description: ID of resource