---
resource_types:

- name: bucket-writer-image-resource
  type: docker-image
  source:
    repository: 18fgsa/s3-resource-simple

resources:

- name: bucket
  type: bucket-writer-image-resource
  source:
    access_key_id: ((AWS_ACCESS_KEY_ID))
    secret_access_key: ((AWS_SECRET_ACCESS_KEY))
    bucket: ((aws-bucket))
    path: public
    region: us-east-1
    options:
    # The options parameter is synonymous with the options that aws cli accepts for sync
    - "--acl 'public-read'"
    - "--delete"

- name: code
  type: git
  source:
    uri: git@gitlab.com:Belcorp-Kampai/kampai-front.git
    branch: master
    private_key: ((front-repo-kanpai))

jobs:
- name: file-upload
  plan:
  - get: code
    trigger: true
  - put: bucket
